on:
  push:
    branches:
      -main
jobs:
  test:
    runs-on: ubuntu-latest
    name: Poetry export requirements.txt file
    steps:
    - uses: actions/checkout@v1
    - name: export
      run: poetry export
    
